### ISSUE TITLE
How to use it ? Could you please give some examples?

### ISSUE THREAD

**Issue by archonwang** [nanego/redmine_introductions#3]
How to use it ? Could you please give some examples?
Thanks.

**Comment by nanego** [comment]
We definitely should add more information in the Readme.

You can get the current example with this configuration:
![capture d ecran 2016-04-21 a 15 30 34](https://cloud.githubusercontent.com/assets/1620522/14710594/44e578ce-07d6-11e6-9a22-9b224a3f10b3.png)

**Comment by archonwang** [comment]
Thanks.
