### ISSUE TITLE
not support redmine 3.2.x

### ISSUE THREAD

**Issue by archonwang** [nanego/redmine_introductions#4]
I used the example in redmine 3.2.x and it failed with no error.

...do you have any idea for i not similar with ruby.. Thanks in advance.

**Comment by nanego** [comment]
Hi. I have just tested the plugin with Redmine 3.2 and it does not seem to work with this latest version. I plan to fix it next week. Thank you for reporting it.

**Comment by nanego** [comment]
Hi. I made a mistake when I tested the plugin with Redmine 3.2 (a typo in the selector). The plugin seems to work fine with the latest version of Redmine.

Can you provide a screenshot of the step you have configured?

**Comment by archonwang** [comment]
@nanego , Thanks,

I have tested it on Redmine 3.2.x and it worked well. Nice work, Thanks.
